# airport_mapping.py

airport_mapping = {
    'BRUSSELS airport': 'BRU',
    'ABU DHABI INTERNATIONAL airport': 'AUH',
    'DUBAI INTERNATIONAL airport': 'DXB',
    'WIEN-SCHWECHAT airport': 'VIE',
    'MONTREAL/PIERRE ELLIOT TRUDEAU INTL, QC airport': 'YUL',
    'GENEVA airport': 'GVA',
    'ZURICH airport': 'ZRH',
    'DOUALA/AEROPORT airport': 'DLA',
    'YAOUNDE/NSIMALEN airport': 'NSI',
    'BEIJING/CAPITAL airport': 'PEK',
    'PRAHA/RUZYNE airport': 'PRG',
    'BERLIN-BRANDENBURG airport': 'BER',
    'FRANKFURT/MAIN airport': 'FRA',
    'HAMBURG airport': 'HAM',
    'MUENCHEN airport': 'MUC',
    'KOBENHAVN/KASTRUP airport': 'CPH',
    'HURGHADA / INTL airport': 'HRG',
    'ATHINAI/ELEFTHERIOS VENIZELOS airport': 'ATH',
    'GRAN CANARIA airport': 'LPA',
    'TENERIFE SUR/REINA SOFIA airport': 'TFS',
    'ALICANTE airport': 'ALC',
    'BILBAO airport': 'BIO',
    'BARCELONA/EL PRAT airport': 'BCN',
    'ADOLFO SUAREZ MADRID-BARAJAS airport': 'MAD',
    'MALAGA/COSTA DEL SOL airport': 'AGP',
    'VALENCIA airport': 'VLC',
    'HELSINKI/VANTAA airport': 'HEL',
    'TOULOUSE/BLAGNAC airport': 'TLS',
    'LYON SAINT-EXUPERY airport': 'LYS',
    'MARSEILLE-PROVENCE airport': 'MRS',
    'NICE-COTE D\'AZUR airport': 'NCE',
    'PARIS-CHARLES DE GAULLE airport': 'CDG',
    'ACCRA/KOTOKA INTERNATIONAL airport': 'ACC',
    'BUDAPEST/LISZT FERENC INTERNATIONAL airport': 'BUD',
    'DUBLIN airport': 'DUB',
    'TEL-AVIV/BEN GURION airport': 'TLV',
    'MILANO/MALPENSA airport': 'MXP',
    'MILANO/LINATE airport': 'LIN',
    'VENEZIA/TESSERA airport': 'VCE',
    'ROMA/FIUMICINO airport': 'FCO',
    'RIGA airport': 'RIX',
    'CASABLANCA/MOHAMMED V airport': 'CMN',
    'NADOR/EL AROUI airport': 'NDR',
    'MARRAKECH/MENARA airport': 'RAK',
    'TANGER/IBN BATOUTA airport': 'TNG',
    'LUQA airport': 'MLA',
    'AMSTERDAM/SCHIPHOL airport': 'AMS',
    'OSLO/GARDERMOEN airport': 'OSL',
    'WARSZAWA/CHOPINA airport': 'WAW',
    'FARO airport': 'FAO',
    'PORTO airport': 'OPO',
    'LISBOA airport': 'LIS',
    'HAMAD INTERNATIONAL airport': 'DOH',
    'BUCURESTI/HENRI COANDA airport': 'OTP',
    'GOTEBORG/LANDVETTER airport': 'GOT',
    'STOCKHOLM/ARLANDA airport': 'ARN',
    'TUNIS/CARTHAGE airport': 'TUN',
    'DJERBA/ZARZIS airport': 'DJE',
    'ANTALYA (MIL-CIV) airport': 'AYT',
    'IZMIR/ADNAN MENDERES airport': 'ADB',
    'ISTANBUL/SABIHA GOKCEN airport': 'SAW',
    'MANCHESTER airport': 'MAN',
    'LONDON HEATHROW airport': 'LHR',
    'NEWARK LIBERTY INTERNATIONAL, NJ. airport': 'EWR',
    'WASHINGTON DULLES INTERNATIONAL, DC. airport': 'IAD',
    'NEW YORK/JOHN F. KENNEDY INTERNATIONAL, NY. airport': 'JFK',
    'CHICAGO - O\'HARE INTERNATIONAL, IL. airport': 'ORD'
}